version: "3"
services:
  db:
    container_name: task6_bd
    build: ./database
    networks:
      - my-net
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql-db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  app:
    container_name: task6
    build: .
    networks:
      - my-net
    volumes:
      - ./log:/app/log
      - ./srs:/app/src
    restart: always
    environment:
      - PORT=${PORT}
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
networks:
  my-net:
    driver: bridge
